// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/bank/v1beta1/proposal.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MintTokensProposal struct {
	Title       string                                   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string                                   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ToAddress   string                                   `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty" yaml:"to_address"`
	Amount      github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,4,rep,name=amount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amount"`
}

func (m *MintTokensProposal) Reset()         { *m = MintTokensProposal{} }
func (m *MintTokensProposal) String() string { return proto.CompactTextString(m) }
func (*MintTokensProposal) ProtoMessage()    {}
func (*MintTokensProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b992919798717ca, []int{0}
}
func (m *MintTokensProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MintTokensProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MintTokensProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MintTokensProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MintTokensProposal.Merge(m, src)
}
func (m *MintTokensProposal) XXX_Size() int {
	return m.Size()
}
func (m *MintTokensProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_MintTokensProposal.DiscardUnknown(m)
}

var xxx_messageInfo_MintTokensProposal proto.InternalMessageInfo

func (m *MintTokensProposal) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MintTokensProposal) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MintTokensProposal) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *MintTokensProposal) GetAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Amount
	}
	return nil
}

func init() {
	proto.RegisterType((*MintTokensProposal)(nil), "cosmos.bank.v1beta1.MintTokensProposal")
}

func init() {
	proto.RegisterFile("cosmos/bank/v1beta1/proposal.proto", fileDescriptor_4b992919798717ca)
}

var fileDescriptor_4b992919798717ca = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xb1, 0x4e, 0xeb, 0x30,
	0x14, 0x86, 0x93, 0xdb, 0xde, 0x4a, 0x75, 0x27, 0x42, 0x91, 0x42, 0x07, 0xa7, 0xca, 0x54, 0x06,
	0x62, 0x0a, 0x4c, 0xdd, 0x68, 0x67, 0x24, 0x54, 0x31, 0xb1, 0x20, 0x27, 0xb1, 0x8a, 0xd5, 0xc6,
	0x27, 0xca, 0x71, 0x11, 0x7d, 0x0b, 0x1e, 0x81, 0x99, 0x27, 0xe9, 0xd8, 0x91, 0xa9, 0xa0, 0x76,
	0x61, 0x61, 0xe1, 0x09, 0x50, 0xed, 0x50, 0x2a, 0x21, 0x31, 0xe5, 0xc4, 0xff, 0xe7, 0xcf, 0xf6,
	0x4f, 0xc2, 0x04, 0x30, 0x03, 0x64, 0x31, 0x57, 0x63, 0x76, 0xdf, 0x8d, 0x85, 0xe6, 0x5d, 0x96,
	0x17, 0x90, 0x03, 0xf2, 0x49, 0x94, 0x17, 0xa0, 0xc1, 0xdb, 0xb7, 0x4c, 0xb4, 0x61, 0xa2, 0x92,
	0x69, 0x35, 0x47, 0x30, 0x02, 0x93, 0xb3, 0xcd, 0x64, 0xd1, 0x16, 0xdd, 0xea, 0x50, 0x6c, 0x75,
	0x09, 0x48, 0xf5, 0x2b, 0xdf, 0x39, 0xce, 0x78, 0x4d, 0x1e, 0x7e, 0xb8, 0xc4, 0xbb, 0x94, 0x4a,
	0x5f, 0xc3, 0x58, 0x28, 0xbc, 0x2a, 0xef, 0xe1, 0x35, 0xc9, 0x7f, 0x2d, 0xf5, 0x44, 0xf8, 0x6e,
	0xdb, 0xed, 0xd4, 0x87, 0xf6, 0xc7, 0x6b, 0x93, 0x46, 0x2a, 0x30, 0x29, 0x64, 0xae, 0x25, 0x28,
	0xff, 0x9f, 0xc9, 0x76, 0x97, 0xbc, 0x73, 0x42, 0x34, 0xdc, 0xf2, 0x34, 0x2d, 0x04, 0xa2, 0x5f,
	0xd9, 0x00, 0xfd, 0x83, 0xcf, 0x65, 0xb0, 0x37, 0xe3, 0xd9, 0xa4, 0x17, 0xfe, 0x64, 0xe1, 0xb0,
	0xae, 0xe1, 0xc2, 0xce, 0x5e, 0x42, 0x6a, 0x3c, 0x83, 0xa9, 0xd2, 0x7e, 0xb5, 0x5d, 0xe9, 0x34,
	0x4e, 0x0f, 0xa3, 0x6d, 0x01, 0x28, 0xbe, 0x0b, 0x88, 0x06, 0x20, 0x55, 0xff, 0x64, 0xbe, 0x0c,
	0x9c, 0xe7, 0xd7, 0xa0, 0x33, 0x92, 0xfa, 0x6e, 0x1a, 0x47, 0x09, 0x64, 0xac, 0x7c, 0xa2, 0xfd,
	0x1c, 0x63, 0x3a, 0x66, 0x7a, 0x96, 0x0b, 0x34, 0x1b, 0x70, 0x58, 0xaa, 0x7b, 0xd5, 0xf7, 0xa7,
	0xc0, 0xe9, 0x0f, 0xe6, 0x2b, 0xea, 0x2e, 0x56, 0xd4, 0x7d, 0x5b, 0x51, 0xf7, 0x71, 0x4d, 0x9d,
	0xc5, 0x9a, 0x3a, 0x2f, 0x6b, 0xea, 0xdc, 0x1c, 0xfd, 0x69, 0x7c, 0xb0, 0x0d, 0x1a, 0x71, 0x5c,
	0x33, 0xdd, 0x9d, 0x7d, 0x05, 0x00, 0x00, 0xff, 0xff, 0x49, 0x22, 0xcd, 0xcc, 0xcc, 0x01, 0x00,
	0x00,
}

func (m *MintTokensProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MintTokensProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MintTokensProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		for iNdEx := len(m.Amount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintProposal(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.ToAddress) > 0 {
		i -= len(m.ToAddress)
		copy(dAtA[i:], m.ToAddress)
		i = encodeVarintProposal(dAtA, i, uint64(len(m.ToAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintProposal(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintProposal(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintProposal(dAtA []byte, offset int, v uint64) int {
	offset -= sovProposal(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MintTokensProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovProposal(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovProposal(uint64(l))
	}
	l = len(m.ToAddress)
	if l > 0 {
		n += 1 + l + sovProposal(uint64(l))
	}
	if len(m.Amount) > 0 {
		for _, e := range m.Amount {
			l = e.Size()
			n += 1 + l + sovProposal(uint64(l))
		}
	}
	return n
}

func sovProposal(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozProposal(x uint64) (n int) {
	return sovProposal(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MintTokensProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProposal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MintTokensProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MintTokensProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProposal
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = append(m.Amount, types.Coin{})
			if err := m.Amount[len(m.Amount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProposal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProposal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProposal(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProposal
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthProposal
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupProposal
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthProposal
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthProposal        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProposal          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupProposal = fmt.Errorf("proto: unexpected end of group")
)
